### ISSUE TITLE
Model size

### ISSUE THREAD

**Issue by chenfsjz** [HongxingGao/XNOR-Net#1]
Hi,I have a problem with your version of xnor net.
after training the cifar10_xnor net,the memory and the final size of the caffemodel just are about the same with the cifar10_full_net, could you give me some suggestions.

**Comment by Ivan-Zhao** [comment]
me too! How to use it?

**Comment by NHZlX** [comment]
@chenfsjz  That's because  the parameters of trained network in the caffemodel are not the final binary storage.

**Comment by HongxingGao** [comment]
@NHZlX  is right. the parameters are stored as float for simiplicity. But you can easily binarize them by sign(x). But please bear in mind, you will also need to compute and store the filter-wise \alpha = |w|/n as stated in the paper.
